import fs from "node:fs";

const pages = [
  { file: "origen-san-nicolas-papa-noel.html", locale: "es", prefix: "" },
  { file: "en/origen-san-nicolas-papa-noel.html", locale: "en", prefix: "../" },
  { file: "fr/origen-san-nicolas-papa-noel.html", locale: "fr", prefix: "../" },
];

const copy = {
  es: {
    title: "Sinterklaas y San Nicolás: tradición neerlandesa y Papá Noel",
    description: "Descubre cómo se celebra Sinterklaas en Países Bajos: su llegada en barco desde España, los zapatos, Pakjesavond, sus símbolos y su origen.",
    main: ({ prefix }) => `<main id="contenido">
<section class="history-hero saint-history-hero"><div class="container saint-history-hero-grid"><div><div class="crumb"><a href="./">Inicio</a> › Historia y tradición › San Nicolás</div><div class="eyebrow">De Nicolás de Mira a Sinterklaas</div><h1>Sinterklaas: la tradición de San Nicolás que viaja desde España.</h1><p>¿Cómo llega San Nicolás a los Países Bajos, por qué los niños dejan un zapato y qué se celebra realmente el 5 de diciembre? Una guía visual para separar historia, folclore y ficción.</p><div class="saint-history-hero-actions"><a class="btn" href="#llegada">DESCUBRIR LA FIESTA ↓</a><a class="text-link" href="san-nicolas.html#estado-publicacion">Ver el cuento ilustrado →</a></div><div class="saint-history-facts" role="list" aria-label="Datos esenciales"><span role="listitem"><strong>Siglo IV</strong>Nicolás de Mira</span><span role="listitem"><strong>Mediados de noviembre</strong>La llegada o intocht</span><span role="listitem"><strong>5 de diciembre</strong>Pakjesavond</span><span role="listitem"><strong>6 de diciembre</strong>Festividad de San Nicolás</span></div></div><figure><img src="${prefix}images/es/san-nicolas-alicante.webp" alt="San Nicolás parte en barco mientras Papá Noel cruza el cielo sobre Alicante" fetchpriority="high" decoding="async" width="799" height="538"/><figcaption>La conexión con Alicante inspira el punto de partida del cuento.</figcaption></figure></div></section>

<section class="saint-history-content"><div class="container history-layout saint-history-layout"><article class="history-article">
<section id="origen"><div class="eyebrow">Tres lugares, tres capas de la historia</div><h2>¿De dónde viene San Nicolás?</h2><p>La respuesta cambia según hablemos del personaje histórico, de sus reliquias o de la tradición neerlandesa. Distinguir esas tres capas permite entender la leyenda sin confundirla con una biografía.</p><div class="origin-route" aria-label="Recorrido histórico y tradicional"><article><span>01</span><strong>Patara y Mira</strong><p>Nicolás nació, según la tradición, en Patara y fue obispo de Mira, ambas en la actual Turquía. Los documentos contemporáneos son escasos, pero su memoria quedó unida a la ayuda a niños, marineros y familias vulnerables.</p></article><article><span>02</span><strong>Bari</strong><p>En 1087, reliquias atribuidas al santo fueron trasladadas a Bari. Por eso gran parte de Europa occidental lo conoce como San Nicolás de Bari, aunque ejerciera como obispo en Mira.</p></article><article><span>03</span><strong>España</strong><p>En el folclore neerlandés, Sinterklaas vive en España y llega por mar. El motivo exacto no tiene una explicación documental única: es una tradición formada y transformada durante siglos.</p></article></div></section>

<section id="llegada"><div class="eyebrow">La celebración en Países Bajos</div><h2>La llegada abre semanas de expectación.</h2><div class="saint-history-feature"><figure><img src="${prefix}images/es/san-nicolas-pieten.webp" alt="San Nicolás y los Pieten reparten regalos por tejados y chimeneas" loading="lazy" decoding="async" width="799" height="538"/></figure><div><h3>De España a los Países Bajos, en barco de vapor</h3><p>A mediados de noviembre, la tradición representa a Sinterklaas llegando desde España en un barco de vapor. Una ciudad acoge la entrada nacional y muchas localidades celebran su propia <em>intocht</em>, con música, desfiles y familias esperando en el puerto o las calles.</p><p>Una vez en tierra, aparece con vestimenta de obispo y continúa el recorrido sobre un caballo blanco. El barco de vapor y buena parte de la iconografía moderna se popularizaron en el siglo XIX.</p></div></div><div class="festival-steps"><article><span>1</span><h3>La <em>intocht</em></h3><p>La llegada pública marca el comienzo de la temporada de Sinterklaas y convierte al puerto en un gran escenario familiar.</p></article><article><span>2</span><h3><em>Schoen zetten</em></h3><p>Los niños dejan un zapato cerca de la chimenea, cantan y suelen añadir una zanahoria o heno para el caballo. A la mañana siguiente pueden encontrar un pequeño regalo o dulce.</p></article><article><span>3</span><h3><em>Pakjesavond</em></h3><p>La noche del 5 de diciembre reúne a familias y amigos para abrir regalos, leer poemas rimados y descubrir envoltorios creativos llamados <em>surprises</em>.</p></article><article><span>4</span><h3>6 de diciembre</h3><p>Es el día tradicional del santo. Tras la gran noche de regalos, el relato cuenta que Sinterklaas regresa a España.</p></article></div></section>

<section id="simbolos"><div class="eyebrow">Lo que simboliza la fiesta</div><h2>Cada objeto cuenta una parte de la tradición.</h2><div class="saint-symbol-grid"><article><span aria-hidden="true">♜</span><h3>La mitra y el báculo</h3><p>Recuerdan que Sinterklaas procede de la memoria de un obispo cristiano, no del aspecto moderno de Papá Noel.</p></article><article><span aria-hidden="true">⚓</span><h3>El barco</h3><p>Convierte su llegada en un viaje colectivo y visible. También enlaza al santo protector de los marineros con los puertos neerlandeses.</p></article><article><span aria-hidden="true">♞</span><h3>El caballo blanco</h3><p>Permite a Sinterklaas recorrer calles y tejados en el imaginario popular mientras sus ayudantes reparten los regalos.</p></article><article><span aria-hidden="true">◒</span><h3>El zapato y la chimenea</h3><p>Representan la entrega nocturna y secreta: un gesto pequeño que conserva la idea de ayudar sin buscar reconocimiento.</p></article><article><span aria-hidden="true">Aa</span><h3>Poemas y letras de chocolate</h3><p>Personalizan cada regalo. Las letras suelen corresponder a la inicial del destinatario y los poemas mezclan cariño y humor.</p></article><article><span aria-hidden="true">✦</span><h3><em>Pepernoten</em> y dulces</h3><p>Galletas especiadas, mazapán y monedas de chocolate forman parte del ambiente compartido durante las semanas de celebración.</p></article></div></section>

<section id="pieten"><div class="eyebrow">Una tradición que también cambia</div><h2>¿Quiénes son los Pieten?</h2><p>Los Pieten ayudan a preparar y repartir regalos, entretienen durante los desfiles y, en el relato actual, entran por las chimeneas. Su representación ha cambiado con el tiempo. La caracterización histórica conocida como <em>Zwarte Piet</em> está vinculada a estereotipos raciales y ha provocado un amplio debate social; muchas celebraciones contemporáneas utilizan <em>roetveegpieten</em>, ayudantes con manchas de hollín, o representaciones diversas.</p><div class="history-callout">Las tradiciones no permanecen inmóviles: conservan símbolos reconocibles, pero también se revisan para que la celebración pueda ser más respetuosa e inclusiva.</div></section>

<section id="espana"><div class="eyebrow">España, Alicante y el cuento</div><h2>¿Vive Sinterklaas realmente en Alicante?</h2><div class="saint-history-feature is-reversed"><figure><img src="${prefix}images/es/san-nicolas-santa.webp" alt="San Nicolás y Papá Noel conversan frente al puerto iluminado de Alicante" loading="lazy" decoding="async" width="799" height="536"/></figure><div><p>La tradición neerlandesa afirma que Sinterklaas llega desde España, pero no existe una única explicación histórica aceptada sobre el origen de esa idea ni un puerto universal e invariable. Alicante mantiene y divulga una conexión popular con esta leyenda.</p><p><strong>El cuento toma esa conexión como punto de partida creativo:</strong> imagina que San Nicolás vive en Alicante y zarpa desde allí cada año. Ese viaje, sus personajes y sus aventuras pertenecen al universo narrativo del libro.</p></div></div></section>

<section class="saint-history-book-bridge" aria-labelledby="cuento-san-nicolas"><div><div class="eyebrow">Del dato histórico a la aventura</div><h2 id="cuento-san-nicolas">Ahora descubre la historia antes de la leyenda.</h2><p><em>El origen de Papá Noel: San Nicolás</em> transforma estos vínculos culturales en un cuento ilustrado sobre generosidad, empatía y el viaje que une Alicante con una tradición europea.</p><a class="btn" href="san-nicolas.html#estado-publicacion">VER EDICIONES Y COMPRAR →</a></div><img src="${prefix}images/es/san-nicolas-cover.webp" srcset="${prefix}images/es/san-nicolas-cover-480.webp 480w, ${prefix}images/es/san-nicolas-cover.webp 888w" sizes="(max-width:850px) 70vw, 280px" alt="Portada de El origen de Papá Noel: San Nicolás" loading="lazy" decoding="async" width="888" height="1226"/></section>

<section id="preguntas" class="saint-history-faq"><div class="eyebrow">Preguntas frecuentes</div><h2>Lo esencial, de un vistazo.</h2><details><summary>¿Cuándo se celebra Sinterklaas en Países Bajos?</summary><p>La temporada comienza con la llegada a mediados de noviembre. La noche principal de regalos, <em>Pakjesavond</em>, es el 5 de diciembre; la festividad tradicional de San Nicolás es el día 6.</p></details><details><summary>¿Cómo llega Sinterklaas?</summary><p>Según el folclore neerlandés, llega desde España en un barco de vapor y después recorre las localidades sobre un caballo blanco.</p></details><details><summary>¿Qué dejan los niños en el zapato?</summary><p>Suelen dejar un dibujo, una carta o una zanahoria para el caballo. Cantan canciones y esperan encontrar después un pequeño regalo, una letra de chocolate o dulces.</p></details><details><summary>¿Sinterklaas y Papá Noel son exactamente el mismo personaje?</summary><p>No. Comparten raíces vinculadas a San Nicolás y a la entrega de regalos, pero su apariencia, fechas y costumbres son diferentes. La tradición neerlandesa influyó en la evolución de Santa Claus.</p></details></section>

<section class="history-sources" aria-labelledby="fuentes-san-nicolas"><div class="eyebrow">Fuentes consultadas</div><h2 id="fuentes-san-nicolas">Historia y tradición documentadas.</h2><ul class="source-list"><li><a href="https://www.openluchtmuseum.nl/nl/verdiep/het-sinterklaasfeest" target="_blank" rel="noopener noreferrer">Nederlands Openluchtmuseum: historia de la fiesta de Sinterklaas</a></li><li><a href="https://npokennis.nl/story/502/hoe-vieren-we-sinterklaas" target="_blank" rel="noopener noreferrer">NPO Kennis: cómo se celebra Sinterklaas</a></li><li><a href="https://www.netherlandsandyou.nl/documents/d/turkiye/shared-heritage-2025" target="_blank" rel="noopener noreferrer">Gobierno de los Países Bajos: llegada y costumbres</a></li><li><a href="https://www.alicante.es/es/noticias/barcala-recibe-al-embajador-paises-bajos-y-divulgaran-leyenda-san-nicolas" target="_blank" rel="noopener noreferrer">Ayuntamiento de Alicante: la conexión popular con la ciudad</a></li><li><a href="https://www.vaticannews.va/es/santos/12/06/s--nicolas-de-bari--obispo-de-mira.html" target="_blank" rel="noopener noreferrer">Vatican News: San Nicolás de Bari</a></li></ul></section>
</article><aside class="history-aside saint-history-aside"><div class="eyebrow">En esta guía</div><nav aria-label="Índice de la guía"><a href="#origen">De Mira a España</a><a href="#llegada">Cómo se celebra</a><a href="#simbolos">Qué simboliza</a><a href="#pieten">Quiénes son los Pieten</a><a href="#espana">Alicante y el cuento</a><a href="#preguntas">Preguntas frecuentes</a></nav><div class="aside-divider"></div><h2>El cuento ilustrado</h2><p>Disponible en español en tapa dura de 91 páginas y Kindle de 46 páginas.</p><a class="btn" href="san-nicolas.html#estado-publicacion">VER EL LIBRO →</a></aside></div></section>
</main>`,
  },
  en: {
    title: "Sinterklaas and Saint Nicholas: Dutch tradition and Santa Claus",
    description: "Discover how Sinterklaas is celebrated in the Netherlands: arrival by boat from Spain, shoes, Pakjesavond, symbols and historical origins.",
    main: ({ prefix }) => `<main id="content">
<section class="history-hero saint-history-hero"><div class="container saint-history-hero-grid"><div><div class="crumb"><a href="./">Home</a> › History and tradition › Saint Nicholas</div><div class="eyebrow">From Nicholas of Myra to Sinterklaas</div><h1>Sinterklaas: the Saint Nicholas tradition that sails from Spain.</h1><p>How does Saint Nicholas arrive in the Netherlands, why do children leave a shoe and what is celebrated on 5 December? A visual guide separating history, folklore and fiction.</p><div class="saint-history-hero-actions"><a class="btn" href="#arrival">DISCOVER THE FESTIVAL ↓</a><a class="text-link" href="san-nicolas.html#publication-status">See the illustrated book →</a></div><div class="saint-history-facts" role="list" aria-label="Key facts"><span role="listitem"><strong>4th century</strong>Nicholas of Myra</span><span role="listitem"><strong>Mid-November</strong>The arrival or intocht</span><span role="listitem"><strong>5 December</strong>Pakjesavond</span><span role="listitem"><strong>6 December</strong>Saint Nicholas Day</span></div></div><figure><img src="${prefix}images/es/san-nicolas-alicante.webp" alt="Saint Nicholas sets sail while Santa Claus crosses the sky above Alicante" fetchpriority="high" decoding="async" width="799" height="538"/><figcaption>The Alicante connection inspires the book's starting point.</figcaption></figure></div></section>
<section class="saint-history-content"><div class="container history-layout saint-history-layout"><article class="history-article">
<section id="origin"><div class="eyebrow">Three places, three layers of the story</div><h2>Where does Saint Nicholas come from?</h2><p>The answer changes depending on whether we mean the historical figure, his relics or Dutch folklore. Keeping these layers apart makes the legend easier to understand.</p><div class="origin-route"><article><span>01</span><strong>Patara and Myra</strong><p>Tradition places Nicholas's birth in Patara and remembers him as bishop of Myra, both in present-day Türkiye. His memory became linked with helping children, sailors and vulnerable families.</p></article><article><span>02</span><strong>Bari</strong><p>Relics attributed to Nicholas were transferred to Bari in 1087. This is why Western Europe often calls him Saint Nicholas of Bari, although he served as bishop in Myra.</p></article><article><span>03</span><strong>Spain</strong><p>In Dutch folklore, Sinterklaas lives in Spain and arrives by sea. There is no single documentary explanation for this part of a tradition shaped over centuries.</p></article></div></section>
<section id="arrival"><div class="eyebrow">The celebration in the Netherlands</div><h2>The arrival begins weeks of anticipation.</h2><div class="saint-history-feature"><figure><img src="${prefix}images/es/san-nicolas-pieten.webp" alt="Saint Nicholas and the Pieten delivering gifts across rooftops and chimneys" loading="lazy" decoding="async" width="799" height="538"/></figure><div><h3>From Spain to the Netherlands by steamboat</h3><p>In mid-November, Sinterklaas is portrayed arriving from Spain on a steamboat. One city hosts the national arrival and many towns hold their own <em>intocht</em>, with music, parades and families waiting by the harbour or along the streets.</p><p>On land he wears a bishop's robes and continues on a white horse. The steamboat and much of today's imagery were popularised in the nineteenth century.</p></div></div><div class="festival-steps"><article><span>1</span><h3>The <em>intocht</em></h3><p>The public arrival opens the Sinterklaas season and turns the harbour into a family celebration.</p></article><article><span>2</span><h3><em>Schoen zetten</em></h3><p>Children place a shoe near the fireplace, sing and often leave a carrot or hay for the horse. A small gift or treat may appear by morning.</p></article><article><span>3</span><h3><em>Pakjesavond</em></h3><p>On 5 December, families and friends exchange presents, read rhyming poems and open imaginative disguises known as <em>surprises</em>.</p></article><article><span>4</span><h3>6 December</h3><p>This is the saint's traditional feast day. After the main gift night, the story says that Sinterklaas returns to Spain.</p></article></div></section>
<section id="symbols"><div class="eyebrow">What the celebration symbolises</div><h2>Every object tells part of the tradition.</h2><div class="saint-symbol-grid"><article><span aria-hidden="true">♜</span><h3>Mitre and crozier</h3><p>They recall Sinterklaas's origin in the memory of a Christian bishop, distinct from modern Santa Claus.</p></article><article><span aria-hidden="true">⚓</span><h3>The boat</h3><p>It turns his return into a collective journey and connects the patron of sailors with Dutch ports.</p></article><article><span aria-hidden="true">♞</span><h3>The white horse</h3><p>In popular imagination it carries Sinterklaas through streets and over rooftops while his helpers deliver gifts.</p></article><article><span aria-hidden="true">◒</span><h3>Shoe and chimney</h3><p>They express the idea of a secret night-time gift: helping without seeking recognition.</p></article><article><span aria-hidden="true">Aa</span><h3>Poems and chocolate letters</h3><p>They make gifts personal. Letters often match the recipient's initial and poems mix affection with playful teasing.</p></article><article><span aria-hidden="true">✦</span><h3><em>Pepernoten</em> and sweets</h3><p>Spiced biscuits, marzipan and chocolate coins help create the shared atmosphere of the season.</p></article></div></section>
<section id="pieten"><div class="eyebrow">A tradition that also changes</div><h2>Who are the Pieten?</h2><p>The Pieten help prepare and deliver presents and entertain crowds during the parades. Their depiction has changed. The historic <em>Zwarte Piet</em> portrayal is associated with racial stereotypes and has caused wide public debate; many contemporary celebrations use <em>roetveegpieten</em>, helpers marked with chimney soot, or more varied representations.</p><div class="history-callout">Traditions are not fixed: familiar symbols remain, while communities also reconsider them so celebrations can become more respectful and inclusive.</div></section>
<section id="spain"><div class="eyebrow">Spain, Alicante and the book</div><h2>Does Sinterklaas really live in Alicante?</h2><div class="saint-history-feature is-reversed"><figure><img src="${prefix}images/es/san-nicolas-santa.webp" alt="Saint Nicholas and Santa Claus by Alicante's illuminated harbour" loading="lazy" decoding="async" width="799" height="536"/></figure><div><p>Dutch tradition says that Sinterklaas arrives from Spain, but there is no single accepted historical explanation or one universal, unchanging departure port. Alicante preserves and promotes a popular connection with the legend.</p><p><strong>The book uses that connection as a creative starting point:</strong> it imagines Saint Nicholas living in Alicante and sailing from there each year. That journey, its characters and adventures belong to the story's fictional world.</p></div></div></section>
<section class="saint-history-book-bridge" aria-labelledby="saint-book"><div><div class="eyebrow">From historical clue to adventure</div><h2 id="saint-book">Now discover the story before the legend.</h2><p><em>The Origin of Santa Claus: Saint Nicholas</em> turns these cultural connections into an illustrated story about generosity, empathy and the journey linking Alicante to a European tradition.</p><a class="btn" href="san-nicolas.html#publication-status">SEE EDITIONS AND BUY →</a></div><img src="${prefix}images/es/san-nicolas-cover.webp" srcset="${prefix}images/es/san-nicolas-cover-480.webp 480w, ${prefix}images/es/san-nicolas-cover.webp 888w" sizes="(max-width:850px) 70vw, 280px" alt="Cover of The Origin of Santa Claus: Saint Nicholas" loading="lazy" decoding="async" width="888" height="1226"/></section>
<section id="questions" class="saint-history-faq"><div class="eyebrow">Frequently asked questions</div><h2>The essentials at a glance.</h2><details><summary>When is Sinterklaas celebrated in the Netherlands?</summary><p>The season begins with the mid-November arrival. The main gift night, <em>Pakjesavond</em>, is 5 December; Saint Nicholas's traditional feast day is 6 December.</p></details><details><summary>How does Sinterklaas arrive?</summary><p>In Dutch folklore, he travels from Spain by steamboat and then rides through towns on a white horse.</p></details><details><summary>What do children leave in their shoes?</summary><p>They may leave a drawing, a letter or a carrot for the horse. They sing and hope to find a small gift, chocolate letter or sweets later.</p></details><details><summary>Are Sinterklaas and Santa Claus exactly the same?</summary><p>No. They share roots connected with Saint Nicholas and gift giving, but their appearance, dates and customs differ. Dutch tradition helped shape the later Santa Claus.</p></details></section>
<section class="history-sources" aria-labelledby="saint-sources"><div class="eyebrow">Sources consulted</div><h2 id="saint-sources">Documented history and tradition.</h2><ul class="source-list"><li><a href="https://www.openluchtmuseum.nl/nl/verdiep/het-sinterklaasfeest" target="_blank" rel="noopener noreferrer">Nederlands Openluchtmuseum: history of Sinterklaas</a></li><li><a href="https://npokennis.nl/story/502/hoe-vieren-we-sinterklaas" target="_blank" rel="noopener noreferrer">NPO Kennis: how Sinterklaas is celebrated</a></li><li><a href="https://www.netherlandsandyou.nl/documents/d/turkiye/shared-heritage-2025" target="_blank" rel="noopener noreferrer">Government of the Netherlands: arrival and customs</a></li><li><a href="https://www.alicante.es/es/noticias/barcala-recibe-al-embajador-paises-bajos-y-divulgaran-leyenda-san-nicolas" target="_blank" rel="noopener noreferrer">Alicante City Council: the city's popular connection</a></li><li><a href="https://www.vaticannews.va/en/saints/12/06/saint-nicholas-of-bari--bishop-of-myra.html" target="_blank" rel="noopener noreferrer">Vatican News: Saint Nicholas of Bari</a></li></ul></section>
</article><aside class="history-aside saint-history-aside"><div class="eyebrow">In this guide</div><nav aria-label="Guide contents"><a href="#origin">From Myra to Spain</a><a href="#arrival">How it is celebrated</a><a href="#symbols">What it symbolises</a><a href="#pieten">Who the Pieten are</a><a href="#spain">Alicante and the book</a><a href="#questions">Frequently asked questions</a></nav><div class="aside-divider"></div><h2>The illustrated story</h2><p>The Spanish edition is available as a 91-page hardback and a 46-page Kindle book.</p><a class="btn" href="san-nicolas.html#publication-status">SEE THE BOOK →</a></aside></div></section>
</main>`,
  },
  fr: {
    title: "Sinterklaas et saint Nicolas : tradition néerlandaise et Père Noël",
    description: "Découvrez la fête de Sinterklaas aux Pays-Bas : arrivée en bateau depuis l’Espagne, chaussures, Pakjesavond, symboles et origines.",
    main: ({ prefix }) => `<main id="contenu">
<section class="history-hero saint-history-hero"><div class="container saint-history-hero-grid"><div><div class="crumb"><a href="./">Accueil</a> › Histoire et tradition › Saint Nicolas</div><div class="eyebrow">De Nicolas de Myre à Sinterklaas</div><h1>Sinterklaas : la tradition de saint Nicolas venue d’Espagne.</h1><p>Comment saint Nicolas arrive-t-il aux Pays-Bas, pourquoi les enfants déposent-ils une chaussure et que célèbre-t-on le 5 décembre ? Un guide visuel qui distingue histoire, folklore et fiction.</p><div class="saint-history-hero-actions"><a class="btn" href="#arrivee">DÉCOUVRIR LA FÊTE ↓</a><a class="text-link" href="san-nicolas.html#statut-publication">Voir le conte illustré →</a></div><div class="saint-history-facts" role="list" aria-label="Repères essentiels"><span role="listitem"><strong>IVe siècle</strong>Nicolas de Myre</span><span role="listitem"><strong>Mi-novembre</strong>L’arrivée ou intocht</span><span role="listitem"><strong>5 décembre</strong>Pakjesavond</span><span role="listitem"><strong>6 décembre</strong>Fête de saint Nicolas</span></div></div><figure><img src="${prefix}images/es/san-nicolas-alicante.webp" alt="Saint Nicolas prend la mer tandis que le Père Noël traverse le ciel d’Alicante" fetchpriority="high" decoding="async" width="799" height="538"/><figcaption>Le lien avec Alicante inspire le point de départ du conte.</figcaption></figure></div></section>
<section class="saint-history-content"><div class="container history-layout saint-history-layout"><article class="history-article">
<section id="origine"><div class="eyebrow">Trois lieux, trois niveaux de récit</div><h2>D’où vient saint Nicolas ?</h2><p>La réponse change selon que l’on parle du personnage historique, de ses reliques ou du folklore néerlandais. Les distinguer permet de comprendre la légende sans la confondre avec une biographie.</p><div class="origin-route"><article><span>01</span><strong>Patara et Myre</strong><p>La tradition situe la naissance de Nicolas à Patara et le présente comme évêque de Myre, dans l’actuelle Türkiye. Sa mémoire s’est liée à l’aide apportée aux enfants, aux marins et aux familles vulnérables.</p></article><article><span>02</span><strong>Bari</strong><p>Des reliques qui lui sont attribuées furent transférées à Bari en 1087. L’Europe occidentale le nomme donc souvent saint Nicolas de Bari, bien qu’il ait été évêque à Myre.</p></article><article><span>03</span><strong>Espagne</strong><p>Dans le folklore néerlandais, Sinterklaas vit en Espagne et arrive par la mer. Il n’existe pas d’explication documentaire unique à cette tradition façonnée pendant des siècles.</p></article></div></section>
<section id="arrivee"><div class="eyebrow">La fête aux Pays-Bas</div><h2>L’arrivée ouvre plusieurs semaines d’attente.</h2><div class="saint-history-feature"><figure><img src="${prefix}images/es/san-nicolas-pieten.webp" alt="Saint Nicolas et les Pieten distribuent des cadeaux sur les toits" loading="lazy" decoding="async" width="799" height="538"/></figure><div><h3>De l’Espagne aux Pays-Bas en bateau à vapeur</h3><p>À la mi-novembre, Sinterklaas est représenté arrivant d’Espagne sur un bateau à vapeur. Une ville accueille l’arrivée nationale et de nombreuses communes organisent leur propre <em>intocht</em>, avec musique, défilés et familles rassemblées.</p><p>À terre, il porte les vêtements d’un évêque et poursuit son parcours sur un cheval blanc. Le bateau à vapeur et une grande partie de l’iconographie actuelle furent popularisés au XIXe siècle.</p></div></div><div class="festival-steps"><article><span>1</span><h3>L’<em>intocht</em></h3><p>L’arrivée publique ouvre la saison de Sinterklaas et transforme le port en grande fête familiale.</p></article><article><span>2</span><h3><em>Schoen zetten</em></h3><p>Les enfants déposent une chaussure près de la cheminée, chantent et laissent parfois une carotte pour le cheval. Un petit cadeau peut apparaître au matin.</p></article><article><span>3</span><h3><em>Pakjesavond</em></h3><p>Le 5 décembre, proches et amis échangent des cadeaux, lisent des poèmes rimés et ouvrent des emballages créatifs appelés <em>surprises</em>.</p></article><article><span>4</span><h3>6 décembre</h3><p>C’est le jour traditionnel du saint. Après la grande soirée des cadeaux, le récit raconte que Sinterklaas repart en Espagne.</p></article></div></section>
<section id="symboles"><div class="eyebrow">Ce que symbolise la fête</div><h2>Chaque objet raconte une partie de la tradition.</h2><div class="saint-symbol-grid"><article><span aria-hidden="true">♜</span><h3>Mitre et crosse</h3><p>Elles rappellent que Sinterklaas vient de la mémoire d’un évêque chrétien, distinct du Père Noël moderne.</p></article><article><span aria-hidden="true">⚓</span><h3>Le bateau</h3><p>Il transforme son retour en voyage collectif et relie le protecteur des marins aux ports néerlandais.</p></article><article><span aria-hidden="true">♞</span><h3>Le cheval blanc</h3><p>Dans l’imaginaire populaire, il porte Sinterklaas dans les rues et sur les toits pendant la distribution.</p></article><article><span aria-hidden="true">◒</span><h3>Chaussure et cheminée</h3><p>Elles expriment l’idée d’un cadeau nocturne et secret : aider sans rechercher la reconnaissance.</p></article><article><span aria-hidden="true">Aa</span><h3>Poèmes et lettres en chocolat</h3><p>Ils personnalisent le cadeau. Les lettres reprennent souvent l’initiale du destinataire et les poèmes mêlent affection et humour.</p></article><article><span aria-hidden="true">✦</span><h3><em>Pepernoten</em> et friandises</h3><p>Biscuits épicés, massepain et pièces en chocolat accompagnent les semaines de célébration.</p></article></div></section>
<section id="pieten"><div class="eyebrow">Une tradition qui évolue aussi</div><h2>Qui sont les Pieten ?</h2><p>Les Pieten aident à préparer et distribuer les cadeaux et animent les défilés. Leur représentation a changé. Le personnage historique appelé <em>Zwarte Piet</em> est associé à des stéréotypes raciaux et a suscité un vaste débat public ; de nombreuses fêtes actuelles utilisent des <em>roetveegpieten</em>, marqués de traces de suie, ou des représentations plus diverses.</p><div class="history-callout">Les traditions ne sont pas immobiles : elles conservent des symboles familiers tout en se transformant pour devenir plus respectueuses et inclusives.</div></section>
<section id="espagne"><div class="eyebrow">Espagne, Alicante et le conte</div><h2>Sinterklaas vit-il vraiment à Alicante ?</h2><div class="saint-history-feature is-reversed"><figure><img src="${prefix}images/es/san-nicolas-santa.webp" alt="Saint Nicolas et le Père Noël devant le port illuminé d’Alicante" loading="lazy" decoding="async" width="799" height="536"/></figure><div><p>La tradition néerlandaise affirme que Sinterklaas arrive d’Espagne, mais il n’existe ni explication historique unique ni port de départ universel et immuable. Alicante entretient et diffuse un lien populaire avec cette légende.</p><p><strong>Le conte transforme ce lien en point de départ créatif :</strong> il imagine saint Nicolas vivant à Alicante et y embarquant chaque année. Ce voyage, ses personnages et ses aventures appartiennent à l’univers fictionnel du livre.</p></div></div></section>
<section class="saint-history-book-bridge" aria-labelledby="livre-saint-nicolas"><div><div class="eyebrow">De l’indice historique à l’aventure</div><h2 id="livre-saint-nicolas">Découvrez maintenant l’histoire avant la légende.</h2><p><em>L’origine du Père Noël : Saint Nicolas</em> transforme ces liens culturels en un conte illustré sur la générosité, l’empathie et le voyage qui relie Alicante à une tradition européenne.</p><a class="btn" href="san-nicolas.html#statut-publication">VOIR LES ÉDITIONS ET ACHETER →</a></div><img src="${prefix}images/es/san-nicolas-cover.webp" srcset="${prefix}images/es/san-nicolas-cover-480.webp 480w, ${prefix}images/es/san-nicolas-cover.webp 888w" sizes="(max-width:850px) 70vw, 280px" alt="Couverture de L’origine du Père Noël : Saint Nicolas" loading="lazy" decoding="async" width="888" height="1226"/></section>
<section id="questions" class="saint-history-faq"><div class="eyebrow">Questions fréquentes</div><h2>L’essentiel en un coup d’œil.</h2><details><summary>Quand célèbre-t-on Sinterklaas aux Pays-Bas ?</summary><p>La saison commence avec l’arrivée à la mi-novembre. La grande soirée des cadeaux, <em>Pakjesavond</em>, a lieu le 5 décembre ; la fête traditionnelle du saint est le 6.</p></details><details><summary>Comment Sinterklaas arrive-t-il ?</summary><p>Selon le folklore néerlandais, il vient d’Espagne en bateau à vapeur puis parcourt les villes sur un cheval blanc.</p></details><details><summary>Que déposent les enfants dans leur chaussure ?</summary><p>Ils peuvent laisser un dessin, une lettre ou une carotte pour le cheval. Ils chantent et espèrent trouver ensuite un petit cadeau ou des friandises.</p></details><details><summary>Sinterklaas et le Père Noël sont-ils exactement le même personnage ?</summary><p>Non. Ils partagent des racines liées à saint Nicolas et aux cadeaux, mais leur apparence, leurs dates et leurs coutumes diffèrent. La tradition néerlandaise a influencé l’évolution de Santa Claus.</p></details></section>
<section class="history-sources" aria-labelledby="sources-saint-nicolas"><div class="eyebrow">Sources consultées</div><h2 id="sources-saint-nicolas">Une histoire et une tradition documentées.</h2><ul class="source-list"><li><a href="https://www.openluchtmuseum.nl/nl/verdiep/het-sinterklaasfeest" target="_blank" rel="noopener noreferrer">Nederlands Openluchtmuseum : histoire de Sinterklaas</a></li><li><a href="https://npokennis.nl/story/502/hoe-vieren-we-sinterklaas" target="_blank" rel="noopener noreferrer">NPO Kennis : comment fête-t-on Sinterklaas ?</a></li><li><a href="https://www.netherlandsandyou.nl/documents/d/turkiye/shared-heritage-2025" target="_blank" rel="noopener noreferrer">Gouvernement des Pays-Bas : arrivée et coutumes</a></li><li><a href="https://www.alicante.es/es/noticias/barcala-recibe-al-embajador-paises-bajos-y-divulgaran-leyenda-san-nicolas" target="_blank" rel="noopener noreferrer">Mairie d’Alicante : le lien populaire avec la ville</a></li><li><a href="https://www.vaticannews.va/es/santos/12/06/s--nicolas-de-bari--obispo-de-mira.html" target="_blank" rel="noopener noreferrer">Vatican News : saint Nicolas de Bari</a></li></ul></section>
</article><aside class="history-aside saint-history-aside"><div class="eyebrow">Dans ce guide</div><nav aria-label="Sommaire du guide"><a href="#origine">De Myre à l’Espagne</a><a href="#arrivee">Comment on le fête</a><a href="#symboles">Ce que cela symbolise</a><a href="#pieten">Qui sont les Pieten</a><a href="#espagne">Alicante et le conte</a><a href="#questions">Questions fréquentes</a></nav><div class="aside-divider"></div><h2>Le conte illustré</h2><p>L’édition espagnole est disponible en relié de 91 pages et en Kindle de 46 pages.</p><a class="btn" href="san-nicolas.html#statut-publication">VOIR LE LIVRE →</a></aside></div></section>
</main>`,
  },
};

const faqs = {
  es: [
    ["¿Cuándo se celebra Sinterklaas en Países Bajos?", "La temporada comienza con la llegada a mediados de noviembre. Pakjesavond se celebra el 5 de diciembre y la festividad tradicional de San Nicolás es el día 6."],
    ["¿Cómo llega Sinterklaas?", "Según el folclore neerlandés, llega desde España en un barco de vapor y después recorre las localidades sobre un caballo blanco."],
    ["¿Qué dejan los niños en el zapato?", "Suelen dejar un dibujo, una carta o una zanahoria para el caballo y esperan encontrar un pequeño regalo o dulces."],
    ["¿Sinterklaas y Papá Noel son el mismo personaje?", "No exactamente. Comparten raíces vinculadas a San Nicolás, pero tienen fechas, apariencia y costumbres diferentes."],
  ],
  en: [
    ["When is Sinterklaas celebrated in the Netherlands?", "The season starts with the mid-November arrival. Pakjesavond is celebrated on 5 December and Saint Nicholas's traditional feast day is 6 December."],
    ["How does Sinterklaas arrive?", "In Dutch folklore he arrives from Spain by steamboat and then travels through towns on a white horse."],
    ["What do children leave in their shoes?", "They may leave a drawing, letter or carrot for the horse and hope to find a small gift or sweets."],
    ["Are Sinterklaas and Santa Claus the same character?", "Not exactly. They share roots connected with Saint Nicholas, but their dates, appearance and customs differ."],
  ],
  fr: [
    ["Quand célèbre-t-on Sinterklaas aux Pays-Bas ?", "La saison commence avec l’arrivée à la mi-novembre. Pakjesavond a lieu le 5 décembre et la fête traditionnelle de saint Nicolas le 6."],
    ["Comment Sinterklaas arrive-t-il ?", "Selon le folklore néerlandais, il vient d’Espagne en bateau à vapeur puis parcourt les villes sur un cheval blanc."],
    ["Que déposent les enfants dans leur chaussure ?", "Ils peuvent laisser un dessin, une lettre ou une carotte pour le cheval et espèrent trouver un petit cadeau ou des friandises."],
    ["Sinterklaas et le Père Noël sont-ils le même personnage ?", "Pas exactement. Ils partagent des racines liées à saint Nicolas, mais leurs dates, leur apparence et leurs coutumes diffèrent."],
  ],
};

for (const page of pages) {
  let html = fs.readFileSync(page.file, "utf8");
  const data = copy[page.locale];
  html = html.replace(/<title>[\s\S]*?<\/title>/, `<title>${data.title}</title>`);
  html = html.replace(/<meta name="description" content="[^"]*"\/>/, `<meta name="description" content="${data.description}"/>`);
  html = html.replace(/<meta property="og:title" content="[^"]*"\/>/, `<meta property="og:title" content="${data.title}"/>`);
  html = html.replace(/<meta property="og:description" content="[^"]*"\/>/, `<meta property="og:description" content="${data.description}"/>`);
  const schema = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Article",
        headline: data.title,
        description: data.description,
        image: "https://jackikun11406jmvv.github.io/images/es/san-nicolas-alicante.webp",
        author: { "@type": "Person", name: "Juan Manuel Vela Vacas" },
        dateModified: "2026-10-09",
        inLanguage: page.locale,
        mainEntityOfPage: `https://jackikun11406jmvv.github.io/${page.locale === "es" ? "" : `${page.locale}/`}origen-san-nicolas-papa-noel.html`,
      },
      {
        "@type": "FAQPage",
        mainEntity: faqs[page.locale].map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })),
      },
    ],
  };
  html = html.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/, `<script type="application/ld+json">${JSON.stringify(schema)}</script>`);
  html = html.replace(/<main\b[\s\S]*?<\/main>/, data.main(page));
  fs.writeFileSync(page.file, html);
}

const homeSections = {
  es: `<section class="history-discoveries" aria-labelledby="historias-reales"><div class="container"><div class="section-title"><div><div class="eyebrow">Más allá de los cuentos</div><h2 id="historias-reales">Descubre las historias detrás de la magia.</h2></div><p>Dos guías ilustradas y documentadas para seguir explorando en familia.</p></div><div class="history-discovery-grid"><a class="history-discovery-card is-perez" href="origen-ratoncito-perez.html"><figure><img src="images/perez-coloma/raton-perez-luis-coloma-casa.webp" alt="La familia del Ratón Pérez en su casa inspirada en el cuento de Luis Coloma" loading="lazy" decoding="async" width="703" height="469"/></figure><div><span>Historia, tradición y curiosidades</span><h3>¿Quién fue Luis Coloma y cómo era su Ratón Pérez?</h3><p>Conoce al rey Bubi, la casa de la familia Pérez y la conexión literaria con Jerez.</p><strong>EXPLORAR LA HISTORIA DE PÉREZ →</strong></div></a><a class="history-discovery-card is-saint" href="origen-san-nicolas-papa-noel.html"><figure><img src="images/es/san-nicolas-pieten.webp" alt="San Nicolás y los Pieten reparten regalos por chimeneas y tejados" loading="lazy" decoding="async" width="799" height="538"/></figure><div><span>Países Bajos, símbolos y tradición</span><h3>¿Cómo llega Sinterklaas desde España?</h3><p>Descubre la <em>intocht</em>, los zapatos, Pakjesavond y qué simboliza cada elemento de la fiesta.</p><strong>DESCUBRIR LA TRADICIÓN DE SAN NICOLÁS →</strong></div></a></div></div></section>`,
  en: `<section class="history-discoveries" aria-labelledby="real-stories"><div class="container"><div class="section-title"><div><div class="eyebrow">Beyond the storybooks</div><h2 id="real-stories">Discover the history behind the magic.</h2></div><p>Two illustrated, documented guides for families to explore together.</p></div><div class="history-discovery-grid"><a class="history-discovery-card is-perez" href="origen-ratoncito-perez.html"><figure><img src="../images/perez-coloma/raton-perez-luis-coloma-casa.webp" alt="The Pérez mouse family in their home inspired by Luis Coloma's story" loading="lazy" decoding="async" width="703" height="469"/></figure><div><span>History, tradition and curiosities</span><h3>Who was Luis Coloma and what was his Little Mouse Pérez like?</h3><p>Meet King Bubi, the Pérez family home and the literary connection with Jerez.</p><strong>EXPLORE THE HISTORY OF PÉREZ →</strong></div></a><a class="history-discovery-card is-saint" href="origen-san-nicolas-papa-noel.html"><figure><img src="../images/es/san-nicolas-pieten.webp" alt="Saint Nicholas and the Pieten delivering gifts over rooftops" loading="lazy" decoding="async" width="799" height="538"/></figure><div><span>The Netherlands, symbols and tradition</span><h3>How does Sinterklaas arrive from Spain?</h3><p>Discover the <em>intocht</em>, shoes, Pakjesavond and the meaning behind the celebration.</p><strong>DISCOVER THE SAINT NICHOLAS TRADITION →</strong></div></a></div></div></section>`,
  fr: `<section class="history-discoveries" aria-labelledby="histoires-reelles"><div class="container"><div class="section-title"><div><div class="eyebrow">Au-delà des contes</div><h2 id="histoires-reelles">Découvrez l’histoire derrière la magie.</h2></div><p>Deux guides illustrés et documentés à explorer en famille.</p></div><div class="history-discovery-grid"><a class="history-discovery-card is-perez" href="origen-ratoncito-perez.html"><figure><img src="../images/perez-coloma/raton-perez-luis-coloma-casa.webp" alt="La famille de la Petite Souris Pérez dans sa maison inspirée du conte de Luis Coloma" loading="lazy" decoding="async" width="703" height="469"/></figure><div><span>Histoire, tradition et curiosités</span><h3>Qui était Luis Coloma et comment décrivait-il Pérez ?</h3><p>Découvrez le roi Bubi, la maison de la famille Pérez et le lien littéraire avec Jerez.</p><strong>EXPLORER L’HISTOIRE DE PÉREZ →</strong></div></a><a class="history-discovery-card is-saint" href="origen-san-nicolas-papa-noel.html"><figure><img src="../images/es/san-nicolas-pieten.webp" alt="Saint Nicolas et les Pieten distribuent des cadeaux sur les toits" loading="lazy" decoding="async" width="799" height="538"/></figure><div><span>Pays-Bas, symboles et tradition</span><h3>Comment Sinterklaas arrive-t-il d’Espagne ?</h3><p>Découvrez l’<em>intocht</em>, les chaussures, Pakjesavond et la signification de chaque élément de la fête.</p><strong>DÉCOUVRIR LA TRADITION DE SAINT NICOLAS →</strong></div></a></div></div></section>`,
};

for (const [file, locale] of [["index.html", "es"], ["en/index.html", "en"], ["fr/index.html", "fr"]]) {
  let html = fs.readFileSync(file, "utf8");
  const editorialPattern = /<section class="(?:perez-discovery|history-discoveries)"[\s\S]*?<\/section>/;
  if (!editorialPattern.test(html)) throw new Error(`No se encontró el bloque editorial en ${file}`);
  html = html.replace(editorialPattern, homeSections[locale]);
  fs.writeFileSync(file, html);
}

console.log("Mejoradas las 3 guías de San Nicolás y las 3 portadas.");
